// <auto-generated />
using System;
using FlightReservation.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightReservation.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251204225538_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("FlightReservation.Core.Airplane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Airplane");
                });

            modelBuilder.Entity("FlightReservation.Core.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirplaneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivalCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirplaneId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FlightReservation.Core.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pnr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePaid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservedCustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservedFlightId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedSeatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReservedCustomerId");

                    b.HasIndex("ReservedFlightId");

                    b.HasIndex("SelectedSeatId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("FlightReservation.Core.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AirplaneId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AirplaneId");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("FlightReservation.Core.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FlightReservation.Core.Admin", b =>
                {
                    b.HasBaseType("FlightReservation.Core.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("FlightReservation.Core.Customer", b =>
                {
                    b.HasBaseType("FlightReservation.Core.User");

                    b.Property<string>("TCKimlikNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("FlightReservation.Core.Flight", b =>
                {
                    b.HasOne("FlightReservation.Core.Airplane", "Airplane")
                        .WithMany()
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airplane");
                });

            modelBuilder.Entity("FlightReservation.Core.Reservation", b =>
                {
                    b.HasOne("FlightReservation.Core.Customer", "ReservedCustomer")
                        .WithMany("Reservations")
                        .HasForeignKey("ReservedCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightReservation.Core.Flight", "ReservedFlight")
                        .WithMany()
                        .HasForeignKey("ReservedFlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightReservation.Core.Seat", "SelectedSeat")
                        .WithMany()
                        .HasForeignKey("SelectedSeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReservedCustomer");

                    b.Navigation("ReservedFlight");

                    b.Navigation("SelectedSeat");
                });

            modelBuilder.Entity("FlightReservation.Core.Seat", b =>
                {
                    b.HasOne("FlightReservation.Core.Airplane", null)
                        .WithMany("Seats")
                        .HasForeignKey("AirplaneId");
                });

            modelBuilder.Entity("FlightReservation.Core.Airplane", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("FlightReservation.Core.Customer", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
